FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Port mặc định của Streamlit
EXPOSE 8501

# Chạy Streamlit
CMD ["streamlit", "run", "frontend/frontend_streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]